// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace y1crm.Models;

public partial class Code
{
    public int Id { get; set; }

    public string Value { get; set; }

    public string Category { get; set; }

    public string Key { get; set; }
}