// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace y1crm.Models;

public partial class crm1Context : DbContext
{
    public crm1Context(DbContextOptions<crm1Context> options)
        : base(options)
    {
    }

    public virtual DbSet<AppSetting> AppSettings { get; set; }

    public virtual DbSet<Code> Codes { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<FollowUpReminder> FollowUpReminders { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Purchase> Purchases { get; set; }

    public virtual DbSet<SubsidyApplication> SubsidyApplications { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_unicode_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<AppSetting>(entity =>
        {
            entity.HasKey(e => e.Key).HasName("PRIMARY");

            entity.ToTable("app_settings", tb => tb.HasComment("系統參數檔"));

            entity.Property(e => e.Key)
                .HasMaxLength(50)
                .HasComment("參數鍵")
                .HasColumnName("key");
            entity.Property(e => e.Value)
                .HasMaxLength(255)
                .HasComment("參數值")
                .HasColumnName("value");
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .HasComment("參數說明")
                .HasColumnName("description");
            entity.Property(e => e.UpdatedAt)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("更新時間")
                .HasColumnType("timestamp")
                .HasColumnName("updated_at");
        });

        modelBuilder.Entity<Code>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("codes");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Category)
                .HasMaxLength(45)
                .HasDefaultValueSql("'類別'")
                .HasColumnName("category");
            entity.Property(e => e.Key)
                .HasMaxLength(45)
                .HasDefaultValueSql("'鍵'")
                .HasColumnName("key");
            entity.Property(e => e.Value)
                .HasMaxLength(45)
                .HasDefaultValueSql("'值'")
                .HasColumnName("value");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("customers", tb => tb.HasComment("客戶主檔"));

            entity.HasIndex(e => e.Name, "idx_customer_name");

            entity.HasIndex(e => e.PhoneMobile, "idx_customer_phone_mobile");

            entity.HasIndex(e => new { e.MailingCity, e.MailingDistrict }, "idx_customer_region");

            entity.HasIndex(e => e.CustomerCode, "uq_customer_code").IsUnique();

            entity.HasIndex(e => e.NationalId, "uq_national_id").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.BirthDate)
                .HasComment("出生年月日(西元)")
                .HasColumnName("birth_date");
            entity.Property(e => e.ConsentDate)
                .HasComment("同意書簽署日期")
                .HasColumnName("consent_date");
            entity.Property(e => e.ConsentSigned)
                .HasComment("是否已簽署個資使用同意書")
                .HasColumnName("consent_signed");
            entity.Property(e => e.ContactName)
                .HasMaxLength(50)
                .HasComment("聯絡人姓名")
                .HasColumnName("contact_name");
            entity.Property(e => e.ContactPhone)
                .HasMaxLength(20)
                .HasComment("聯絡人電話")
                .HasColumnName("contact_phone");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp")
                .HasColumnName("created_at");
            entity.Property(e => e.CustomerCode)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("客戶編號(表單手寫編號)")
                .HasColumnName("customer_code");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .HasComment("通訊電子信箱")
                .HasColumnName("email");
            entity.Property(e => e.Gender)
                .HasComment("性別")
                .HasColumnType("enum('M','F')")
                .HasColumnName("gender");
            entity.Property(e => e.HouseholdCity)
                .HasMaxLength(20)
                .HasComment("戶籍地址-縣市")
                .HasColumnName("household_city");
            entity.Property(e => e.HouseholdDetail)
                .HasMaxLength(100)
                .HasComment("戶籍地址-路街/段/巷/弄/號/樓")
                .HasColumnName("household_detail");
            entity.Property(e => e.HouseholdDistrict)
                .HasMaxLength(20)
                .HasComment("戶籍地址-鄉鎮市區")
                .HasColumnName("household_district");
            entity.Property(e => e.HouseholdVillage)
                .HasMaxLength(20)
                .HasComment("戶籍地址-村里")
                .HasColumnName("household_village");
            entity.Property(e => e.MailingCity)
                .HasMaxLength(20)
                .HasComment("通訊地址-縣市")
                .HasColumnName("mailing_city");
            entity.Property(e => e.MailingDetail)
                .HasMaxLength(100)
                .HasComment("通訊地址-路街/段/巷/弄/號/樓")
                .HasColumnName("mailing_detail");
            entity.Property(e => e.MailingDistrict)
                .HasMaxLength(20)
                .HasComment("通訊地址-鄉鎮市區")
                .HasColumnName("mailing_district");
            entity.Property(e => e.MailingVillage)
                .HasMaxLength(20)
                .HasComment("通訊地址-村里")
                .HasColumnName("mailing_village");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("姓名")
                .HasColumnName("name");
            entity.Property(e => e.NationalId)
                .HasMaxLength(10)
                .HasComment("身分證字號(個資，注意存取權限)")
                .HasColumnName("national_id");
            entity.Property(e => e.Notes)
                .HasComment("備註")
                .HasColumnType("text")
                .HasColumnName("notes");
            entity.Property(e => e.PhoneHome)
                .HasMaxLength(20)
                .HasComment("通訊電話(市話)")
                .HasColumnName("phone_home");
            entity.Property(e => e.PhoneMobile)
                .HasMaxLength(20)
                .HasComment("通訊電話(個人)")
                .HasColumnName("phone_mobile");
            entity.Property(e => e.RegistrationDate)
                .HasComment("建檔日期")
                .HasColumnName("registration_date");
            entity.Property(e => e.SubsidyApplied)
                .HasComment("是否申請補助(表單勾選)")
                .HasColumnName("subsidy_applied");
            entity.Property(e => e.UpdatedAt)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp")
                .HasColumnName("updated_at");
            entity.Property(e => e.UpdatedBy)
                .HasMaxLength(45)
                .HasComment("最後修改者")
                .HasColumnName("updated_by");
        });

        modelBuilder.Entity<FollowUpReminder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("follow_up_reminders", tb => tb.HasComment("回診/保養提醒"));

            entity.HasIndex(e => e.CustomerId, "fk_reminders_customer");

            entity.HasIndex(e => e.PurchaseId, "fk_reminders_purchase");

            entity.HasIndex(e => new { e.ScheduledDate, e.Status }, "idx_reminders_scheduled");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CompletedDate)
                .HasComment("實際完成日期")
                .HasColumnName("completed_date");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp")
                .HasColumnName("created_at");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.Notes)
                .HasColumnType("text")
                .HasColumnName("notes");
            entity.Property(e => e.PurchaseId)
                .HasComment("關聯的購買紀錄(可為空)")
                .HasColumnName("purchase_id");
            entity.Property(e => e.ReminderType)
                .IsRequired()
                .HasComment("回診/保養/電池更換/調機/其他")
                .HasColumnType("enum('follow_up','maintenance','battery_replacement','tuning','other')")
                .HasColumnName("reminder_type");
            entity.Property(e => e.ScheduledDate)
                .HasComment("預定提醒日期")
                .HasColumnName("scheduled_date");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasDefaultValueSql("'pending'")
                .HasColumnType("enum('pending','completed','cancelled')")
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Customer).WithMany(p => p.FollowUpReminders)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("fk_reminders_customer");

            entity.HasOne(d => d.Purchase).WithMany(p => p.FollowUpReminders)
                .HasForeignKey(d => d.PurchaseId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("fk_reminders_purchase");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("products", tb => tb.HasComment("產品型錄"));

            entity.HasIndex(e => new { e.Brand, e.ModelName }, "uq_product").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Brand)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("品牌")
                .HasColumnName("brand");
            entity.Property(e => e.Category)
                .IsRequired()
                .HasDefaultValueSql("'hearing_aid'")
                .HasComment("分類:助聽器/耳膜/電池/配件/其他")
                .HasColumnType("enum('hearing_aid','earmold','battery','accessory','other')")
                .HasColumnName("category");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp")
                .HasColumnName("created_at");
            entity.Property(e => e.IsActive)
                .IsRequired()
                .HasDefaultValueSql("'1'")
                .HasComment("是否仍在售/在用")
                .HasColumnName("is_active");
            entity.Property(e => e.ModelName)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("型號")
                .HasColumnName("model_name");
            entity.Property(e => e.UnitPrice)
                .HasPrecision(10, 2)
                .HasComment("參考單價")
                .HasColumnName("unit_price");
        });

        modelBuilder.Entity<Purchase>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("purchases", tb => tb.HasComment("購買/租借紀錄"));

            entity.HasIndex(e => e.ProductId, "fk_purchases_product");

            entity.HasIndex(e => e.CustomerId, "idx_purchases_customer");

            entity.HasIndex(e => e.WarrantyEndDate, "idx_purchases_warranty_end");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp")
                .HasColumnName("created_at");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.EarSide)
                .HasComment("左耳/右耳/雙耳")
                .HasColumnType("enum('left','right','both')")
                .HasColumnName("ear_side");
            entity.Property(e => e.Notes)
                .HasColumnType("text")
                .HasColumnName("notes");
            entity.Property(e => e.PaymentStatus)
                .IsRequired()
                .HasDefaultValueSql("'unpaid'")
                .HasColumnType("enum('unpaid','partial','paid')")
                .HasColumnName("payment_status");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.Quantity)
                .HasDefaultValueSql("'1'")
                .HasColumnName("quantity");
            entity.Property(e => e.SerialNumber)
                .HasMaxLength(50)
                .HasComment("機身序號")
                .HasColumnName("serial_number");
            entity.Property(e => e.TransactionDate)
                .HasComment("交易日期")
                .HasColumnName("transaction_date");
            entity.Property(e => e.TransactionType)
                .IsRequired()
                .HasDefaultValueSql("'purchase'")
                .HasComment("購買/租借/維修/退貨")
                .HasColumnType("enum('purchase','rental','repair','return')")
                .HasColumnName("transaction_type");
            entity.Property(e => e.UnitPrice)
                .HasPrecision(10, 2)
                .HasComment("實際成交單價")
                .HasColumnName("unit_price");
            entity.Property(e => e.UpdatedAt)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp")
                .HasColumnName("updated_at");
            entity.Property(e => e.WarrantyEndDate)
                .HasComment("保固到期日")
                .HasColumnName("warranty_end_date");
            entity.Property(e => e.WarrantyStartDate)
                .HasComment("保固起始日")
                .HasColumnName("warranty_start_date");

            entity.HasOne(d => d.Customer).WithMany(p => p.Purchases)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_purchases_customer");

            entity.HasOne(d => d.Product).WithMany(p => p.Purchases)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("fk_purchases_product");
        });

        modelBuilder.Entity<SubsidyApplication>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("subsidy_applications", tb => tb.HasComment("補助申請追蹤"));

            entity.HasIndex(e => e.CustomerId, "fk_subsidy_customer");

            entity.HasIndex(e => e.Status, "idx_subsidy_status");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ApplicationDate)
                .HasComment("申請日期")
                .HasColumnName("application_date");
            entity.Property(e => e.ApprovalDate)
                .HasComment("核准/駁回日期")
                .HasColumnName("approval_date");
            entity.Property(e => e.ApprovedAmount)
                .HasPrecision(10, 2)
                .HasComment("核准補助金額")
                .HasColumnName("approved_amount");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp")
                .HasColumnName("created_at");
            entity.Property(e => e.CustomerId).HasColumnName("customer_id");
            entity.Property(e => e.Notes)
                .HasColumnType("text")
                .HasColumnName("notes");
            entity.Property(e => e.ProgramName)
                .HasMaxLength(100)
                .HasComment("補助方案名稱(如:衛福部/社會局)")
                .HasColumnName("program_name");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasDefaultValueSql("'preparing'")
                .HasColumnType("enum('preparing','submitted','under_review','approved','rejected')")
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .ValueGeneratedOnAddOrUpdate()
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp")
                .HasColumnName("updated_at");

            entity.HasOne(d => d.Customer).WithMany(p => p.SubsidyApplications)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_subsidy_customer");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("users");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Cdate)
                .HasMaxLength(6)
                .HasColumnName("cdate");
            entity.Property(e => e.Level)
                .HasMaxLength(16)
                .HasColumnName("level");
            entity.Property(e => e.Password)
                .HasMaxLength(45)
                .HasColumnName("password");
            entity.Property(e => e.Realname)
                .HasMaxLength(45)
                .HasColumnName("realname");
            entity.Property(e => e.Username)
                .HasMaxLength(45)
                .HasColumnName("username");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}