// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace y1crm.Models;

/// <summary>
/// 客戶主檔
/// </summary>
public partial class Customer
{
    public ulong Id { get; set; }

    /// <summary>
    /// 客戶編號(表單手寫編號)
    /// </summary>
    public string CustomerCode { get; set; }

    /// <summary>
    /// 建檔日期
    /// </summary>
    public DateOnly RegistrationDate { get; set; }

    /// <summary>
    /// 姓名
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 性別
    /// </summary>
    public string Gender { get; set; }

    /// <summary>
    /// 身分證字號(個資，注意存取權限)
    /// </summary>
    public string NationalId { get; set; }

    /// <summary>
    /// 出生年月日(西元)
    /// </summary>
    public DateOnly? BirthDate { get; set; }

    /// <summary>
    /// 通訊電話(市話)
    /// </summary>
    public string PhoneHome { get; set; }

    /// <summary>
    /// 通訊電話(個人)
    /// </summary>
    public string PhoneMobile { get; set; }

    /// <summary>
    /// 通訊電子信箱
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 聯絡人姓名
    /// </summary>
    public string ContactName { get; set; }

    /// <summary>
    /// 聯絡人電話
    /// </summary>
    public string ContactPhone { get; set; }

    /// <summary>
    /// 通訊地址-縣市
    /// </summary>
    public string MailingCity { get; set; }

    /// <summary>
    /// 通訊地址-鄉鎮市區
    /// </summary>
    public string MailingDistrict { get; set; }

    /// <summary>
    /// 通訊地址-村里
    /// </summary>
    public string MailingVillage { get; set; }

    /// <summary>
    /// 通訊地址-路街/段/巷/弄/號/樓
    /// </summary>
    public string MailingDetail { get; set; }

    /// <summary>
    /// 戶籍地址-縣市
    /// </summary>
    public string HouseholdCity { get; set; }

    /// <summary>
    /// 戶籍地址-鄉鎮市區
    /// </summary>
    public string HouseholdDistrict { get; set; }

    /// <summary>
    /// 戶籍地址-村里
    /// </summary>
    public string HouseholdVillage { get; set; }

    /// <summary>
    /// 戶籍地址-路街/段/巷/弄/號/樓
    /// </summary>
    public string HouseholdDetail { get; set; }

    /// <summary>
    /// 是否申請補助(表單勾選)
    /// </summary>
    public bool SubsidyApplied { get; set; }

    /// <summary>
    /// 是否已簽署個資使用同意書
    /// </summary>
    public bool ConsentSigned { get; set; }

    /// <summary>
    /// 同意書簽署日期
    /// </summary>
    public DateOnly? ConsentDate { get; set; }

    /// <summary>
    /// 備註
    /// </summary>
    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    /// <summary>
    /// 最後修改者
    /// </summary>
    public string UpdatedBy { get; set; }

    public virtual ICollection<FollowUpReminder> FollowUpReminders { get; set; } = new List<FollowUpReminder>();

    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();

    public virtual ICollection<SubsidyApplication> SubsidyApplications { get; set; } = new List<SubsidyApplication>();
}