// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace y1crm.Models;

/// <summary>
/// 回診/保養提醒
/// </summary>
public partial class FollowUpReminder
{
    public ulong Id { get; set; }

    public ulong CustomerId { get; set; }

    /// <summary>
    /// 關聯的購買紀錄(可為空)
    /// </summary>
    public ulong? PurchaseId { get; set; }

    /// <summary>
    /// 回診/保養/電池更換/調機/其他
    /// </summary>
    public string ReminderType { get; set; }

    /// <summary>
    /// 預定提醒日期
    /// </summary>
    public DateOnly ScheduledDate { get; set; }

    public string Status { get; set; }

    /// <summary>
    /// 實際完成日期
    /// </summary>
    public DateOnly? CompletedDate { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Purchase Purchase { get; set; }
}