// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace y1crm.Models;

/// <summary>
/// 產品型錄
/// </summary>
public partial class Product
{
    public ulong Id { get; set; }

    /// <summary>
    /// 品牌
    /// </summary>
    public string Brand { get; set; }

    /// <summary>
    /// 型號
    /// </summary>
    public string ModelName { get; set; }

    /// <summary>
    /// 分類:助聽器/耳膜/電池/配件/其他
    /// </summary>
    public string Category { get; set; }

    /// <summary>
    /// 參考單價
    /// </summary>
    public decimal? UnitPrice { get; set; }

    /// <summary>
    /// 是否仍在售/在用
    /// </summary>
    public bool? IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();
}