// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace y1crm.Models;

/// <summary>
/// 購買/租借紀錄
/// </summary>
public partial class Purchase
{
    public ulong Id { get; set; }

    public ulong CustomerId { get; set; }

    public ulong? ProductId { get; set; }

    /// <summary>
    /// 購買/租借/維修/退貨
    /// </summary>
    public string TransactionType { get; set; }

    /// <summary>
    /// 左耳/右耳/雙耳
    /// </summary>
    public string EarSide { get; set; }

    /// <summary>
    /// 機身序號
    /// </summary>
    public string SerialNumber { get; set; }

    public uint Quantity { get; set; }

    /// <summary>
    /// 實際成交單價
    /// </summary>
    public decimal? UnitPrice { get; set; }

    /// <summary>
    /// 交易日期
    /// </summary>
    public DateOnly TransactionDate { get; set; }

    /// <summary>
    /// 保固起始日
    /// </summary>
    public DateOnly? WarrantyStartDate { get; set; }

    /// <summary>
    /// 保固到期日
    /// </summary>
    public DateOnly? WarrantyEndDate { get; set; }

    public string PaymentStatus { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<FollowUpReminder> FollowUpReminders { get; set; } = new List<FollowUpReminder>();

    public virtual Product Product { get; set; }
}