// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace y1crm.Models;

/// <summary>
/// 補助申請追蹤
/// </summary>
public partial class SubsidyApplication
{
    public ulong Id { get; set; }

    public ulong CustomerId { get; set; }

    /// <summary>
    /// 補助方案名稱(如:衛福部/社會局)
    /// </summary>
    public string ProgramName { get; set; }

    /// <summary>
    /// 申請日期
    /// </summary>
    public DateOnly? ApplicationDate { get; set; }

    public string Status { get; set; }

    /// <summary>
    /// 核准補助金額
    /// </summary>
    public decimal? ApprovedAmount { get; set; }

    /// <summary>
    /// 核准/駁回日期
    /// </summary>
    public DateOnly? ApprovalDate { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Customer Customer { get; set; }
}